- name: Install 
  vars_files: 
    - vars/vars.yml
  hosts: "{{ host }}"
  gather_facts: no
  become: yes    

  tasks:
    
    - name: Get latest info
      uri:
        url: "{{ nibiru_githubapi_url }}"
        return_content: true
      register: nibiru_info

    - name: Get version 
      set_fact: version="{{ nibiru_info.json.tag_name }}"


    # - name: Filter assets for amd64 platform
    #   set_fact:
    #     asset_file_name: "{{ nibiru_info.json.assets | selectattr('name', 'match', '.*linux_amd64.*')|map(attribute='name') | list }}"

    # - name: Filter assets for amd64 platform
    #   set_fact:
    #     asset_url: "{{ nibiru_info.json.assets | selectattr('name', 'match', '.*linux_amd64.*')|map(attribute='browser_download_url') | list }}"
    
    - name: Filter assets for amd64 platform
      set_fact:
        asset_file_name: "{{ nibiru_info.json.assets[5].name }}"

    - name: Filter assets for amd64 platform
      set_fact:
        asset_url: "{{ nibiru_info.json.assets[5].browser_download_url }}"
    
    - name: Get Dockerfile from URL
      get_url:
        url: "{{ asset_url }}"
        dest: "./download_file"


    
   