- name: Run Nibiru validator setup
  vars_files: 
    - vars/vars.yml
    
  hosts: "{{ host }}"
  gather_facts: no
  become: yes


  tasks:
  
      

    - name: Get sync status inside container
      community.docker.docker_container_exec: 
        container: "{{ container_name }}"
        command: sh -c "curl http://localhost:26657/status | jq .result.sync_info.catching_up"
      register: sync_out


    - name: Validate whether the node synced
      assert:
        that: 
          - sync_out.stdout == "false"
        fail_msg: "The node is not synced!!!! Please wait for a while"

    - name: Upgrade to a Validator
      community.docker.docker_container_exec: 
        container: "{{ container_name }}"
        command: sh -c ' printf "%s\n" {{ password4key }} | {{ command }} tx staking create-validator --amount 1000000unibi --commission-rate "0.1" --commission-max-rate "0.20" --commission-max-change-rate "0.1" --min-self-delegation "1" --pubkey=$({{ command }} tendermint show-validator)  --moniker {{ NIBIRU_MONIKER }} --chain-id {{ NIBIRU_CHAIN }} --from {{ NIBIRU_WALLET }} --fees 5000unibi --yes'
      register: out_validator
      

    - name: Print all details about Validator result
      ansible.builtin.debug:
        var: out_validator

        

