- name: Install 
  vars_files: 
    - vars/vars.yml
  hosts: "{{ host }}"
  gather_facts: no
  become: yes    
  vars:
    my_string: "[abcde]"

  tasks:
    
    - name: Get latest info
      uri:
        url: "{{ nibiru_githubapi_url }}"
        return_content: true
      register: nibiru_info

    - name: Get version 
      set_fact: version="{{ nibiru_info.json.tag_name }}"

    # - name: Get amd64 asset name
    #   set_fact:
    #     asset_url: "{{ nibiru_info.json.assets[item].name }}"
    #   loop: "{{ range(nibiru_info.json.assets) | list }}"
    #   when: "'amd64' in item.name"
    #   loop_control:
    #     index_var: item

    - name: Filter assets for amd64 platform
      set_fact:
        asset_file_name: "{{ nibiru_info.json.assets | selectattr('name', 'match', '.*linux_amd64.*')|map(attribute='name') | list }}"

    - name: Filter assets for amd64 platform
      set_fact:
        asset_url: "{{ nibiru_info.json.assets | selectattr('name', 'match', '.*linux_amd64.*')|map(attribute='browser_download_url') | list }}"
    

      

    - name: Print variables
      debug:
        msg: "{{ asset_url }} {{ version }}"

    - name: Trim first and last two characters from string
      set_fact:
        my_string: "{{ my_string[2:-2] }}"

