- name: Install 
  vars_files: 
    - vars/vars.yml
  hosts: "{{ host }}"
  gather_facts: no
  become: yes    

  tasks:
    
    - name: Get latest info
      uri:
        url: "{{ nibiru_githubapi_url }}"
        return_content: true
      register: nibiru_info

    - name: Get version 
      set_fact: version="{{ nibiru_info.json.tag_name }}"

    - name: Get amd64 asset name
      set_fact:
        asset_url: "{% for asset in nibiru_info.json.assets %}{% if 'arm' in asset.name %}{{ asset.url }}{% endif %}{% endfor %}"

    - name: Print variables
      debug:
        msg: "{{ asset_url }}"