- name: Run Niburu wallet setup
  vars_files:
    - vars/vars.yml
    
  hosts: "{{ host }}"
  gather_facts: no
  become: yes

  pre_tasks:
    - pause:
        prompt: "Input your recovery mnemonic"
        echo: no
      when: ask_recovery != "no" 
      register: recovery_mnemonic

  tasks:

    - name: Set recovery mnemonic
      set_fact: recovery="{{ recovery_mnemonic.user_input }}"
      when: recovery_mnemonic.user_input is defined
  
  


