
  - name: Check if 
    get_url:
        force: true
        url: "{{ nibiru_genesis_file }}"
        dest: /dev/null
    register: results
    ignore_errors: true

  - name: Stop in case docker not exists
    assert: 
      that:
        - result.status != 200
        - result.size == 0
      fail_msg: "The resource {{ nibiru_genesis_file }} is not available!"  

  
  
