
  - name: Check if Docker is installed
    get_url:
        force: true
        url: "{{ nibiru_geneis_file }}"
        dest: /dev/null
    register: results
    ignore_errors: true

  - name: Stop in case docker not exists
    assert: 
      that:
        - result|failed
      fail_msg: "The resource {{ nibiru_geneis_file }} is not available!"  

  
  
