
  - name: Check if 
    get_url:
        force: true
        url: "{{ nibiru_genesis_file }}"
        dest: /dev/null
    register: result
    ignore_errors: true

  - name: Stop in case genesis configuration file not available
    assert: 
      that:
        - not result.failed
        - result.size == 0
      fail_msg: "The resource {{ nibiru_genesis_file }} is not available!"  

  
  
